name: samh_task
description: A Simple Travel Agency Booking App.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localization: any
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1
  month_year_picker: ^0.3.0+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/images/
    - assets/lang/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900

    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri/ElMessiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/ElMessiri/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri/ElMessiri-Bold.ttf
          weight: 700
